server:
  port: 5600
  servlet:
    context-path: /olympus
    
spring:
  application:
    name: olympus-services
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect